backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "Pages"
    label: "Pages"
    delete: false
    files:
    - label: "Home"
      name: "Home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Flamingo Restaurant'
          name: "infoData"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Paragraph", name: "paragraph", widget: "text"}
            - { label: "Button", name: "button", widget: "boolean"}
            - { label: "ButtonLabel", name: "buttonLabel", widget: "string"}
            - { label: "ButtonPath", name: "buttonPath", widget: "string"}
            - { label: "Reverse", name: "reverse", widget: "boolean"}
            - { label: "Color", name: "color", widget: "color", allowInput: true}
            - { label: "Image", name: "image", widget: "image"}
            - { label: "Alt", name: "alt", widget: "string"}
            - { label: "Font", name: "font", widget: "color", allowInput: true}
    - label: "Menu Page"
      name: "Menu"
      file: "content/menu.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
        - label: "Menu Items"   
          name: "MenuData"
          widget: list
          fields: 
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "string", default: ""}
            - { label: "Price", name: "price", widget: "number", step: 0.01}
            - { label: "Tag", name: "tag", widget: "list"}
            - { label: "Image", name: "image", widget: "image"}
